# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 981a364d9637d0b6938b52612a8cdf33858720832f744df528aa34fa51eeb7b21551501741e263dd93c611634351cf6adc4d2e3b13cc967710f2c48b2b2b7fe2

test:
  secret_key_base: 9366b92f903bde44ce926c746ee91bffeb2b01cd3cdef55b291166ac7d325d5d04c665d27dd9106823122c346829667c4790fe7732a95a72aa22b985356ff34b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
